export const GET_BOOKS_ASYNC = "GET_BOOKS_ASYNC";
export const EDIT_BOOK_ASYNC = "EDIT_BOOK_ASYNC";
export const GET_BOOK_BY_ID_ASYNC = "GET_BOOK_BY_ID_ASYNC";
export const GET_FILTERED_BOOKS_ASYNC = "GET_FILTERED_BOOKS_ASYNC";
export const CHECK_SUCCESS = "CHECK_SUCCESS";

export const GET_BOOKS = "GET_BOOKS";
export const GET_FILTERED_BOOKS = "GET_FILTERED_BOOKS";
export const GET_BOOK_BY_ID = "GET_BOOK_BY_ID";
export const EDIT_BOOK = "EDIT_BOOK";
